apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels: 
    app: wordpress
spec:
  selector:
    app: wordpress
    tier: mysql
  ports:
  - port: 3306
  type: ClusterIP
  clusterIP: None

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: wordpress
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dc
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mysql-secret
              key: root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-pv-storage
          mountPath: /var/lib/mysql 
      volumes:
      - name: mysql-pv-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim


