apiVersion: v1
kind: Pod
metadata:
  name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: mypvc
  containers:
    - name: mycontainer
      image: httpd
      volumeMounts:
        - mountPath: "/var/www/html"
          name: pv-storage
