apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 3
  selector:
    matchExpressions:
      - { key: tier, operator: In, values: [ ws ] }
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        tier: ws
        app: web
    spec:
      containers:
      - name: myc1
        image: vimal13/apache-webserver-php