apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 3
  selector:
    tier: ws
  template:
    metadata:
      name: myapp
      labels:
        tier: ws
    spec:
      containers:
        - name: mycon
          image: vimal13/apache-webserver-php
        
